services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./prisma:/app/prisma
      - ./public:/app/public
      - ./src:/app/src
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy && 
             npx prisma db seed &&
             npm start"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
